version: "3.6"

services:
  api:
    container_name: sso-app
    image: sso-app
    ports:
        - 8080:8080
        - 44844:44844
    environment:
      REDIS_URL: redis:6379
      # The environment in which the application is running (string)
      ENV: dev
      # Path to sqlite store (string)
      STORE_PATH: ./app/storage/sso.db
      # Authentication service standart TTL (time.Duration)
      AUTHENTICATION_TOKEN_TTL: ${AUTHENTICATION_TOKEN_TTL}
      # gRPC server port (uint16)
      GRPC_PORT: ${GRPC_PORT}
      # REST server port (uint16)
      REST_PORT: ${REST_PORT}
      # Redis user (string)
      REDIS_USER: ${REDIS_USER}
      # Redis user's password (string)
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      # Redis database connection (int)
      REDIS_DB: ${REDIS_DB}
      # Redis server host (string)
      REDIS_HOST: ${REDIS_HOST}
      # Redis server port (uint16)
      REDIS_PORT: ${REDIS_PORT}

    command: ./app/main
    volumes:
      - ./storage/:/app/storage/

    build:
      dockerfile: Dockerfile
  
  # app:
  #   image: golang:1.23.6-alpine
  #   volumes:
  #     - .:/go/src/go-with-compose
  #   working_dir: /go/src/go-with-compose
  #   command: go run ./cmd/sso/main.go
  #   environment:
  #     REDIS_URL: redis:6379
  #     # The environment in which the application is running (string)
  #     ENV: dev
  #     # Path to sqlite store (string)
  #     STORE_PATH: ${STORE_PATH}
  #     # Authentication service standart TTL (time.Duration)
  #     AUTHENTICATION_TOKEN_TTL: ${AUTHENTICATION_TOKEN_TTL}
  #     # gRPC server port (uint16)
  #     GRPC_PORT: ${GRPC_PORT}
  #     # REST server port (uint16)
  #     REST_PORT: ${REST_PORT}
  #     # Redis user (string)
  #     REDIS_USER: ${REDIS_USER}
  #     # Redis user's password (string)
  #     REDIS_PASSWORD: ${REDIS_PASSWORD}
  #     # Redis database connection (int)
  #     REDIS_DB: ${REDIS_DB}
  #     # Redis server host (string)
  #     REDIS_HOST: ${REDIS_HOST}
  #     # Redis server port (uint16)
  #     REDIS_PORT: ${REDIS_PORT}
