version: "3"


includes:
  sdk:
    taskfile: ./sso-sdk/Taskfile.yaml
    dir: ./sdk

env:

  # APP_SETTINGS

  # path to active config file
  CONFIG_PATH: ./config/local.yaml
  # path to sqlite storage
  STORE_PATH: ./storage/sso.db

  # output of the go coverage tool
  COVERAGE_FILE: cover.out

vars:
  FLAG_CONFIG: --config=$CONFIG_PATH

tasks:

  # MAIN

  run:
    desc: Run main application
    cmd: go run ./cmd/sso {{.FLAG_CONFIG}}

  build:
    desc: Builds application
    deps: 
      - lint
    cmds:
      - 'go build -o bin/ ./cmd/sso/main.go'
    sources:
      - ./*.go,
      - ./**/*.go

  # TESTING

  test:
    desc: Test all packages
    cmd: go test -v -cover -coverprofile=$COVERAGE_FILE ./internal/...
  
  test-coverage:
    desc: Generates coverage html after testing
    aliases:
      - cover
    deps:
      - test
    cmd: go tool cover -html=$COVERAGE_FILE

  mock:
    desc: Generates all mocks
    cmd: go generate ./...

  # TOOLS

  dev:
    desc: Build and start app with file listener (hot reload)
    deps: 
      - build
    silent: true
    watch: true
    cmd: ./bin/main {{.FLAG_CONFIG}}
    sources: 
      - ./*.go,
      - ./**/*.go

  lint:
    desc: Lint all files
    cmd: fieldalignment -fix ./...
    ignore_error: true
    
# DOCS
# swag init -g ./cmd/sso/main.go -o ./docs
# swagger generate client -f ./docs/swagger.yaml
# swagger generate spec -o ./docs/swagger-v1.yaml