version: "3"

dotenv: ['.env']

tasks:
  generate-go:
    aliases:
      - gen-go
    desc: "Generate golang code from proto files"
    cmd: sh $SCRIPTS_DIR/generate.sh

  test:
    desc: "Test all packages"
    cmd: go test -v -cover -coverprofile=$COVERAGE_FILE ./...
  
  test-coverage:
    aliases:
      - cover
    desc: "Generates coverage html after testing"
    deps:
      - test
    cmd: go tool cover -html=$COVERAGE_FILE