version: "3"

includes:
  sdk:
    taskfile: ./sso-sdk/Taskfile_{{OS}}.yaml
    optional: true

dotenv: ['.env']

env:
  # internal folder
  INTERNAL_WILDCARD: ./internal/...
  # coverage file
  COVERAGE_FILE: ./tests/cover.out

tasks:

  # MAIN

  run-local:
    desc: Run main application
    cmd: go run ./cmd/sso

  run-docker:
    desc: "Run sso docker server"
    cmd: docker compose -f ./deploy/compose/sso-app.docker-compose.yaml up -d --build

  build-local:
    desc: Builds application
    cmds:
      - 'go build -o bin/ ./cmd/sso/main.go'
    sources:
      - ./*.go,
      - ./**/*.go

  build-docker:
    desc: Build Docker image
    cmd: 'docker build -t sso-app . -f ./deploy/docker/sso-app.Dockerfile'

  copy-bin:
    desc: copy binary from sso-app image to local storage
    deps:
      - build-docker
    cmds:
      - 'docker create --name extract sso-app'
      - 'docker cp extract:/app/main ./bin/main'
      - 'docker rm extract'

  # TESTING

  test:
    desc: Test all packages
    cmd: sh scripts/testing.sh $COVERAGE_FILE
  
  test-coverage:
    desc: Generates coverage html after testing
    aliases: [cover]
    deps:
      - test
    cmd: go tool cover -html="$COVERAGE_FILE"

  bench:
    desc: Run benchmarks
    cmd: go test -bench . -benchmem ./internal/lib/collections -cpuprofile=./profiles/cpu.out -memprofile=./profiles/mem.out

  prof:
    desc: Use pprof 
    cmds:
      - go tool pprof --pdf ./profiles/cpu.out > ./profiles/cpu-prof.pdf
      - go tool pprof --pdf ./profiles/mem.out > ./profiles/mem-prof.pdf 

  mock:
    desc: Generates all mocks
    cmd: mockery --config=./tools/testing/.mockery.yml

  # TOOLS

  dev:
    desc: Build and start app with file listener (hot reload)
    deps: [build-local]
    silent: true
    watch: true
    cmd: ./bin/main {{.FLAG_CONFIG}}
    sources: 
      - ./*.go,
      - ./**/*.go

  lint:
    desc: Lint all files
    cmd: fieldalignment -fix $INTERNAL_WILDCARD
    ignore_error: true
      
  graph:
    desc: Generate dependency graph in pdf
    cmd: go mod graph | modgraphviz | dot -Tpdf -o graph.pdf
    
  init:
    desc: Initialize project (python is required)
    cmds:
      - python ./scripts/create_dotenv.py

  # DOCS

  docs:
    desc: Generate docs
    env:
      SWAG: swag init -g ./cmd/sso/main.go
    cmds:
      # make internal docs (go-based)
      - $SWAG -o ./internal/gen/swagger --ot go
      # make sdk docs (json,yaml)
      - $SWAG -o ./sso-sdk/swagger --ot json,yaml --instanceName sso_swagger
      # make env example
      - go run ./cmd/sso/main.go --config.doc=./docs/.env.example

  # SECURITY
  security:
    desc: Run security checks
    cmds:
      - gosec ./...

  generate_hmac_key:
    desc: Generate hmac_secret_file used to configure dgraph secrets so far
    aliases: [gen-hmac]
    cmd: tr -dc 'a-zA-Z0-9' < /dev/urandom | dd bs=1 count=32 of=./deploy/compose/dgraph/acl/hmac_secret