version: "3"

includes:
  sdk:
    taskfile: ./sso-sdk/Taskfile.yaml
    optional: true

dotenv: ['.env']

vars:
  FLAG_CONFIG: --config=$CONFIG_PATH
  INTERNAL_WILDCARD: ./internal/...

tasks:

  # MAIN

  run:
    desc: Run main application
    cmd: go run ./cmd/sso {{.FLAG_CONFIG}}

  build:
    desc: Builds application
    deps: 
      - lint
    cmds:
      - 'go build -o bin/ ./cmd/sso/main.go'
    sources:
      - ./*.go,
      - ./**/*.go

  # TESTING

  test:
    desc: Test all packages
    cmd: sh scripts/testing.sh $COVERAGE_FILE
  
  test-coverage:
    desc: Generates coverage html after testing
    aliases:
      - cover
    deps:
      - test
    cmd: go tool cover -html=$COVERAGE_FILE

  mock:
    desc: Generates all mocks
    cmd: go generate {{.INTERNAL_WILDCARD}}

  # TOOLS

  dev:
    desc: Build and start app with file listener (hot reload)
    deps: 
      - build
    silent: true
    watch: true
    cmd: ./bin/main {{.FLAG_CONFIG}}
    sources: 
      - ./*.go,
      - ./**/*.go

  lint:
    desc: Lint all files
    cmd: fieldalignment -fix {{.INTERNAL_WILDCARD}}
    ignore_error: true
    
  # DOCS

  swagger:
    desc: Generate swagger docs
    cmds:
      # make internal docs (go-based)
      - swag init -g ./cmd/sso/main.go -o ./docs --ot go
      # make sdk docs (json,yaml)
      - swag init -g ./cmd/sso/main.go -o ./sso-sdk/docs --ot json,yaml

# swag init -g ./cmd/sso/main.go -o ./docs
# swagger generate client -f ./docs/swagger.yaml
# swagger generate spec -o ./docs/swagger-v1.yaml

# swagger generate client -f ./sso-sdk/docs/swagger.yaml -c sso/client -m sso/models
