server:
  http_listen_port: 9080
  grpc_listen_port: 0

clients:
  - url: http://192.168.12.41:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: DEV_lfp-mobile.cbr.ru
      __path__: C:\Services\lfp-mobile.cbr.ru\logs\*.log

  - targets:
      - localhost
    labels:
      job: DEV_lfp-assmr.cbr.ru
      __path__: C:\Services\lfp-assmr.cbr.ru\logs\*.log
  
  - targets:
      - localhost
    labels:
      job: DEV_chat-mobile-rubricator.cbr.ru
      __path__: C:\Services\chat-mobile-rubricator.cbr.ru\logs\*.log

  - targets:
      - localhost
    labels:
      job: DEV_exchange-assmr.cbr.ru
      __path__: C:\Services\exchange-assmr.cbr.ru\logs\*.log

  - targets:
      - localhost
    labels:
      job: DEV_ib-assmr.cbr.ru
      __path__: C:\Services\ib-assmr.cbr.ru\logs\*.log

  - targets:
      - localhost
    labels:
      job: DEV_padmin-assmr.cbr.ru
      __path__: C:\Services\padmin-assmr.cbr.ru\logs\*.log      
      
  - targets:
      - localhost
    labels:
      job: DEV_surveys-assmr.cbr.ru
      __path__: C:\Services\surveys-assmr.cbr.ru\logs\*.log          
      
# |= "Please check the std error output for the stack trace"