server:
  http_listen_port: 9080
  grpc_listen_port: 0

clients:
  - url: http://192.168.12.41:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: DEV_push-proxy-lfp.cbr.ru
      __path__: C:\services\push-proxy-lfp.cbr.ru\logs\*.log

  - targets:
      - localhost
    labels:
      job: DEV_sms-proxy
      __path__: C:\services\sms-proxy\logs\*.log