# This Docker Compose file can be used to quickly boot up Dgraph Zero
# and Alpha in different Docker containers.
# It mounts /tmp/data on the host machine to /dgraph within the
# container. You will need to change /tmp/data to a more appropriate location.
# Run `docker-compose up` to start Dgraph.
version: "3.2"
services:
  zero:
    container_name: zero
    image: dgraph/dgraph:latest
    volumes:
      - ./data:/dgraph
    ports:
      - 5080:5080
      - 6080:6080
    restart: on-failure
    command: dgraph zero --my=zero:5080
  alpha:
    container_name: alpha
    image: dgraph/dgraph:latest
    volumes:
      - ./data:/dgraph
    ports:
      - 8080:8080
      - 9080:9080
    restart: on-failure
    command: dgraph alpha --my=alpha:7080 --zero=zero:5080 --security whitelist=localhost,172.24.0.1
  ratel:
  # A simple web interface for exploring Dgraph data.
    container_name: ratel
    image: dgraph/ratel:latest
    ports:
      - 8000:8000

