version: "3"

tasks:

  run:
    desc: "Run dgraph docker server"
    dir: '{{.TASKFILE_DIR}}'
    cmd: docker compose -f docker-compose.yaml up -d --build

  stop:
    desc: "Stop dgraph docker server"
    dir: '{{.TASKFILE_DIR}}'
    cmd: docker stop zero alpha ratel