version: "3.6"

name: sso

networks:
  redis:
  dgraph:

services:
  
  app-1:
    container_name: app-1
    image: sso-app
    ports:
      - ${REST_PORT}:4080
      - ${GRPC_PORT}:4090
    env_file:
      - ../../.env
    volumes:
      - ../../storage/:/app/storage/
    depends_on:
      - redis
      - alpha
    networks:
      - dgraph
      - redis

  redis:
    image: redis:latest
    container_name: redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_USER=${REDIS_USER}
      - REDIS_USER_PASSWORD=${REDIS_USER_PASSWORD}
    volumes:
      - ./data/redis:/data
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    command: >
      sh -c '
        mkdir -p /usr/local/etc/redis &&
        echo "bind 0.0.0.0" > /usr/local/etc/redis/redis.conf &&
        echo "requirepass $REDIS_PASSWORD" >> /usr/local/etc/redis/redis.conf &&
        echo "appendonly yes" >> /usr/local/etc/redis/redis.conf &&
        echo "appendfsync everysec" >> /usr/local/etc/redis/redis.conf &&
        echo "user default on nopass ~* +@all" > /usr/local/etc/redis/users.acl &&
        echo "user $REDIS_USER on >$REDIS_USER_PASSWORD ~* +@all" >> /usr/local/etc/redis/users.acl &&
        redis-server /usr/local/etc/redis/redis.conf --aclfile /usr/local/etc/redis/users.acl
      '
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true
    networks:
      - redis

  zero:
    container_name: zero1
    image: dgraph/dgraph:latest
    volumes:
      - ./data/dgraph:/dgraph
    ports:
      - 5080:5080
      - 6080:6080
    restart: on-failure
    command: dgraph zero --my=zero1:5080
    networks:
      - dgraph

  alpha:
    container_name: alpha
    image: dgraph/dgraph:latest
    environment:
      DGRAPH_ALPHA_ACL: secret-file=/acl/hmac_secret
      DGRAPH_ALPHA_SECURITY: whitelist=localhost,10.0.0.0/8,172.0.0.0/8,192.168.0.0/16
    volumes:
      - ./data/dgraph:/dgraph
      - ./dgraph/acl:/acl
    ports:
      - 8080:8080
      - ${DGRAPH_GRPC_PORT}:${DGRAPH_GRPC_PORT}
    restart: on-failure
    command: dgraph alpha --my=alpha:7080 --zero=zero:5080
    networks:
      - dgraph

  ratel:
    container_name: ratel
    image: dgraph/ratel:latest
    ports:
      - 8000:8000
    networks:
      - dgraph