version: "3"

tasks:

  run:
    desc: "Run mssql docker server"
    dir: '{{.TASKFILE_DIR}}'
    cmd: docker compose -f docker-compose.yaml up -d --build

  stop:
    desc: "Stop both nodes"
    dir: '{{.TASKFILE_DIR}}'
    cmd: docker stop grafana loki promtail