# env: "dev" # dev, prod
# store_path: ./storage/sso.db

services:

  authentication:
    token_ttl: 1h

# ports are meant to be in range (8000,65535)
servers:

  grpc:
    server_options:
      port: 44844
      timeout: 5s

  rest:
    server_options:
      port: 8080
      timeout: 5s
  
  routes:
    server_options:
      port: 3000
      timeout: 5s

cache:

  redis:
    options:
      user: my_user
      password: my_user_password
      db: 0
      host: localhost
      port: 6380

redis:
  user: my_user
  password: my_user_password
  db: 1
  host: someshit
  port: 6381