version: "3"

tasks:
  
  run:
    desc: "Run redis docker server"
    dir: '{{.TASKFILE_DIR}}'
    cmd: docker compose -f docker-compose.yaml up -d --build

  stop:
    desc: "Stop redis docker server"
    dotenv: ['.env']
    dir: '{{.TASKFILE_DIR}}'
    cmd: docker stop $CONTAINER_NAME